export const DEFAULT_CFG = {
  is_enabled: false,
  dry_run: true,
  refresh_interval_secs: 10,
  enter_score_threshold: 15,
  max_open_pairs: 5,
  target_utilization_pct: 60,
  min_pair_notional_usd: 300,
  max_pair_notional_usd: 3000,
  switch_min_advantage: 5,
  switch_confirm_rounds: 3,
  entry_conf_min: 0.55,
  hold_conf_min: 0.45,
  max_total_utilization_pct: 100,
  reserve_floor_pct: 2,
  fee_buffer_pct: 0.5,
  slippage_buffer_pct: 0.5,
  margin_buffer_pct: 1.0,
  min_capacity_pct: 12,
  max_impact_pct: 0.3,
  rebalance_min_relative_adv_pct: 5,
  rebalance_min_absolute_adv_usd_day: 0.5,
  data_stale_threshold_seconds: 20,
  api_fail_circuit_count: 5,
  execution_retry_max_rounds: 2,
  execution_retry_backoff_secs: 8,
  delta_epsilon_abs_usd: 5,
  delta_epsilon_nav_pct: 0.01,
  repair_timeout_secs: 20,
  repair_retry_rounds: 2,
  circuit_breaker_on_repair_fail: true,
  basis_shock_exit_z: 4,
  portfolio_dd_soft_pct: -2,
  portfolio_dd_hard_pct: -4,
};

export const AUTO_TERM_HELP = {
  auto_control: '自动执行总控面板，负责候选扫描、开平仓调度与风控联动。',
  is_enabled: '总开关。开启后按扫描间隔持续运行自动决策；关闭后仅保留手动操作。',
  dry_run: '模拟模式只生成计划与日志，不下真实订单。',
  circuit_breaker_on_repair_fail: '敞口修复连续失败时触发熔断，暂停自动执行，避免风险扩大。',
  contract_entry_execution: '合约腿的默认下单模式与杠杆设置。',
  cross_margin_mode: '使用全仓保证金，共享账户保证金，减少单仓爆仓概率。',
  fixed_leverage_2x: '默认按 2 倍杠杆计算名义与保证金需求。',
  safety_cushion: '开仓前预留的风险缓冲资金，不参与可用名义分配。',
  unhedged_tolerance: '允许的净敞口偏差上限，超过即触发修复逻辑。',
  '执行与重试': '控制调度频率、执行失败后的重试次数与重试间隔。',
  '信号与准入': '控制入场评分、换仓门槛与置信度过滤。',
  '资金与组合': '控制总占用、目标占用、组合规模、单对最小名义与单对最大名义。',
  '动态安全垫': '按成本与保证金动态预留安全垫，防止高波动时过度开仓。',
  '成交与容量': '限制流动性不足和冲击成本过高的标的。',
  '换仓门槛': '控制换仓必须达到的相对与绝对收益增量。',
  '无敞口修复': '控制净敞口容忍区间和修复确认参数。',
  '数据与风控': '控制数据新鲜度、接口熔断和组合回撤防线。',
  refresh_interval_secs: '每轮自动扫描与执行调度的时间间隔。',
  execution_retry_max_rounds: '同一执行任务允许重试的最大轮数。',
  execution_retry_backoff_secs: '重试前等待时间，避免连续撞单或瞬时故障重试。',
  enter_score_threshold: '严格评分最低要求，低于该值不允许新开仓。',
  switch_min_advantage: '换仓候选相对当前持仓需要至少超出的收益比例。',
  switch_confirm_rounds: '换仓条件需连续满足的轮数，降低抖动换仓。',
  entry_conf_min: '开仓所需的最低置信度。',
  hold_conf_min: '持仓继续保留所需的最低置信度。',
  max_total_utilization_pct: '总资金利用率硬上限，超过后禁止新增仓位。',
  target_utilization_pct: '常态目标资金利用率，用于自动分配开仓预算。',
  max_open_pairs: '允许同时持有的最大币对数量。',
  min_pair_notional_usd: '单个币对允许开仓的最小名义价值。',
  max_pair_notional_usd: '单个币对允许开仓的最大名义价值（开仓单腿口径）。',
  reserve_floor_pct: '安全垫最小保底比例。',
  fee_buffer_pct: '为手续费预留的缓冲比例。',
  slippage_buffer_pct: '为成交滑点预留的缓冲比例。',
  margin_buffer_pct: '为保证金波动预留的缓冲比例。',
  min_capacity_pct: '候选容量低于该比例时不参与自动开仓。',
  max_impact_pct: '预估冲击成本高于该比例时禁止开仓。',
  rebalance_min_relative_adv_pct: '换仓所需的最小相对收益增益。',
  rebalance_min_absolute_adv_usd_day: '换仓所需的最小绝对收益增益（按天）。',
  delta_epsilon_abs_usd: '净敞口允许的绝对偏差阈值（USDT）。',
  delta_epsilon_nav_pct: '净敞口允许的 NAV 相对偏差阈值。',
  repair_timeout_secs: '单轮敞口修复的超时时间。',
  repair_retry_rounds: '敞口修复后连续确认达标的轮数。',
  data_stale_threshold_seconds: '行情/账户数据超过该时长视为陈旧数据。',
  api_fail_circuit_count: '连续 API 失败次数达到后触发风控熔断。',
  basis_shock_exit_z: '基差偏离历史均值的 Z 值超过阈值时触发退出保护。',
  portfolio_dd_soft_pct: '组合触发软回撤后的温和降风险阈值。',
  portfolio_dd_hard_pct: '组合触发硬回撤后的强制降风险阈值。',
  drawdown_watermark: '回撤计算使用的高水位。重置后会以当前 NAV 作为新的风险起点。',
  drawdown_reset_button: '将组合回撤高水位重置为当前 NAV，用于解除历史峰值导致的硬回撤阻断。',
};

export const CFG_FIELD_META = {
  refresh_interval_secs: { label: '扫描间隔', addonAfter: '秒', min: 3, max: 300, step: 1, int: true },
  execution_retry_max_rounds: { label: '执行重试轮数', min: 0, max: 20, step: 1, int: true },
  execution_retry_backoff_secs: { label: '重试退避', addonAfter: '秒', min: 1, max: 600, step: 1, int: true },
  enter_score_threshold: { label: '入场评分阈值', min: 0, max: 100, step: 0.1 },
  switch_min_advantage: { label: '换仓最小优势', addonAfter: '%', min: 0, max: 200, step: 0.1 },
  switch_confirm_rounds: { label: '换仓确认轮数', min: 1, max: 20, step: 1, int: true },
  entry_conf_min: { label: '入场置信度下限', min: 0, max: 1, step: 0.01 },
  hold_conf_min: { label: '持仓置信度下限', min: 0, max: 1, step: 0.01 },
  max_total_utilization_pct: { label: '总资金利用率上限', addonAfter: '%', min: 1, max: 100, step: 0.5 },
  target_utilization_pct: { label: '目标资金利用率', addonAfter: '%', min: 1, max: 100, step: 0.5 },
  reserve_floor_pct: { label: '安全垫下限', addonAfter: '%', min: 0, max: 30, step: 0.1 },
  fee_buffer_pct: { label: '手续费缓冲', addonAfter: '%', min: 0, max: 30, step: 0.1 },
  slippage_buffer_pct: { label: '滑点缓冲', addonAfter: '%', min: 0, max: 30, step: 0.1 },
  margin_buffer_pct: { label: '保证金缓冲', addonAfter: '%', min: 0, max: 30, step: 0.1 },
  max_open_pairs: { label: '最大持仓币对数', min: 1, max: 100, step: 1, int: true },
  min_pair_notional_usd: { label: '单对最小名义', addonAfter: 'USD', min: 1, max: 1000000, step: 1 },
  max_pair_notional_usd: { label: '单对最大名义', addonAfter: 'USD', min: 1, max: 1000000, step: 1 },
  min_capacity_pct: { label: '容量下限', addonAfter: '%', min: 0, max: 100, step: 0.1 },
  max_impact_pct: { label: '冲击成本上限', addonAfter: '%', min: 0.01, max: 100, step: 0.01 },
  rebalance_min_relative_adv_pct: { label: '换仓相对增益门槛', addonAfter: '%', min: 0, max: 200, step: 0.1 },
  rebalance_min_absolute_adv_usd_day: { label: '换仓绝对增益门槛', addonAfter: 'USD/天', min: 0, max: 100000, step: 0.1 },
  delta_epsilon_abs_usd: { label: '敞口容忍(绝对)', addonAfter: 'USD', min: 0, max: 100000, step: 0.5 },
  delta_epsilon_nav_pct: { label: '敞口容忍(NAV)', addonAfter: '%', min: 0, max: 100, step: 0.001 },
  repair_timeout_secs: { label: '敞口修复超时', addonAfter: '秒', min: 1, max: 3600, step: 1, int: true },
  repair_retry_rounds: { label: '敞口修复确认轮数', min: 1, max: 20, step: 1, int: true },
  data_stale_threshold_seconds: { label: '数据陈旧阈值', addonAfter: '秒', min: 0, max: 3600, step: 1, int: true },
  api_fail_circuit_count: { label: '接口熔断计数', min: 1, max: 200, step: 1, int: true },
  basis_shock_exit_z: { label: '基差冲击退出Z', min: 0, max: 20, step: 0.1 },
  portfolio_dd_soft_pct: { label: '组合软回撤阈值', addonAfter: '%', min: -100, max: 0, step: 0.1 },
  portfolio_dd_hard_pct: { label: '组合硬回撤阈值', addonAfter: '%', min: -100, max: 0, step: 0.1 },
};

export const CFG_SECTIONS = [
  { title: '执行与重试', keys: ['refresh_interval_secs', 'execution_retry_max_rounds', 'execution_retry_backoff_secs'] },
  { title: '信号与准入', keys: ['enter_score_threshold', 'switch_min_advantage', 'switch_confirm_rounds', 'entry_conf_min', 'hold_conf_min'] },
  { title: '资金与组合', keys: ['max_total_utilization_pct', 'target_utilization_pct', 'max_open_pairs', 'min_pair_notional_usd', 'max_pair_notional_usd'] },
  { title: '动态安全垫', keys: ['reserve_floor_pct', 'fee_buffer_pct', 'slippage_buffer_pct', 'margin_buffer_pct'] },
  { title: '成交与容量', keys: ['min_capacity_pct', 'max_impact_pct'] },
  { title: '换仓门槛', keys: ['rebalance_min_relative_adv_pct', 'rebalance_min_absolute_adv_usd_day'] },
  { title: '无敞口修复', keys: ['delta_epsilon_abs_usd', 'delta_epsilon_nav_pct', 'repair_timeout_secs', 'repair_retry_rounds'] },
  { title: '数据与风控', keys: ['data_stale_threshold_seconds', 'api_fail_circuit_count', 'basis_shock_exit_z', 'portfolio_dd_soft_pct', 'portfolio_dd_hard_pct'] },
];
