export const AUTO_CFG_FIELD_LABELS = {
  enter_score_threshold: '入场评分阈值',
  entry_conf_min: '入场置信度下限',
  max_open_pairs: '最大持仓对数',
  target_utilization_pct: '目标资金利用率(%)',
  min_pair_notional_usd: '单对最小本金(USDT)',
  max_impact_pct: '最大冲击成本(%)',
  switch_confirm_rounds: '换仓确认轮数',
  rebalance_min_relative_adv_pct: '换仓相对增益门槛(%)',
  rebalance_min_absolute_adv_usd_day: '换仓绝对增益门槛(USDT/天)',
  hold_conf_min: '持有置信度下限',
  switch_min_advantage: '换仓最小优势(%)',
  max_exchange_utilization_pct: '单交易所利用率上限(%)',
  max_symbol_utilization_pct: '单币种利用率上限(%)',
  min_capacity_pct: '容量下限(%)',
  portfolio_dd_hard_pct: '组合硬回撤阈值(%)',
};

export const READINESS_REASON_LABELS = {
  universe_empty: '候选池为空',
  universe_missing_dates: '部分日期缺少机会池',
  snapshot_empty: '15m快照为空',
  snapshot_coverage_low: '15m快照覆盖率偏低',
  previous_run_deadband_blocked: '上次回测被死区阈值阻断',
  previous_run_universe_empty: '上次回测因候选池为空未执行',
};

export const DELTA_REASON_LABELS = {
  adv_below_abs_deadband: '绝对增益未达阈值',
  adv_below_rel_deadband: '相对增益未达阈值',
  no_delta_plan: '当前无调仓差额',
};

export const IMPORT_JOB_TYPE_LABELS = {
  import_snapshots: '快照导入',
  import_funding: 'Funding导入',
};

export const defaultParams = {
  days: 15,
  top_n: 120,
  initial_nav_usd: 10000,
  min_rate_pct: 0.01,
  min_perp_volume: 1000000,
  min_spot_volume: 1000000,
  min_basis_pct: 0,
  require_cross_exchange: false,
  enter_score_threshold: 0,
  entry_conf_min: 0.55,
  hold_conf_min: 0.45,
  max_open_pairs: 5,
  target_utilization_pct: 60,
  min_pair_notional_usd: 300,
  max_exchange_utilization_pct: 35,
  max_symbol_utilization_pct: 10,
  min_capacity_pct: 12,
  max_impact_pct: 0.3,
  switch_min_advantage: 5,
  switch_confirm_rounds: 3,
  rebalance_min_relative_adv_pct: 5,
  rebalance_min_absolute_adv_usd_day: 0.5,
  portfolio_dd_hard_pct: -4,
  data_stale_max_buckets: 3,
};

export const defaultSearchParams = {
  days: 30,
  top_n: 120,
  initial_nav_usd: 10000,
  min_rate_pct: 0.01,
  min_perp_volume: 1000000,
  min_spot_volume: 1000000,
  min_basis_pct: 0,
  require_cross_exchange: false,
  hold_conf_min: 0.45,
  max_exchange_utilization_pct: 35,
  max_symbol_utilization_pct: 10,
  min_capacity_pct: 12,
  switch_min_advantage: 5,
  portfolio_dd_hard_pct: -4,
  data_stale_max_buckets: 3,
  train_days: 7,
  test_days: 3,
  step_days: 3,
  train_top_k: 3,
  max_trials: 24,
  random_seed: 42,
  enter_score_threshold_values: '0,5,10,15',
  entry_conf_min_values: '0.5,0.55,0.6',
  max_open_pairs_values: '3,5,7',
  target_utilization_pct_values: '50,60,70',
  min_pair_notional_usd_values: '200,300,500',
  max_impact_pct_values: '0.2,0.3,0.4',
  switch_confirm_rounds_values: '2,3,4',
  rebalance_min_relative_adv_pct_values: '3,5,8',
  rebalance_min_absolute_adv_usd_day_values: '0.3,0.5,1.0',
};
